language: php
sudo: false

notifications:
  email: false

addons:
  postgresql: "9.4"

php:
  - 7.0
  #- 7.1
  #- 7.2

matrix:
  allow_failures:
  exclude:
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  fast_finish: true

env:
  global:
    - IGNORE_PATHS=thirdparty BEHAT=yes
  matrix:
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=master


before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master #MOODLE_36_STABLE
      install:
        - moodle-plugin-ci install --no-init
      script:
        - moodle-plugin-ci phplint
        - moodle-plugin-ci phpcpd
        - moodle-plugin-ci phpmd
        - moodle-plugin-ci codechecker
        - moodle-plugin-ci savepoints
        # - moodle-plugin-ci mustache
        - moodle-plugin-ci grunt
        - moodle-plugin-ci validate
    # Smaller build matrix for development builds
    - stage: develop
      php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master #MOODLE_36_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - moodle-plugin-ci phpunit --coverage-clover
        - moodle-plugin-ci behat

# Unit tests and behat tests against full matrix.
install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat
after_success:
  - bash <(curl -s https://codecov.io/bash)